# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - go test -v ./...
  lint:
    cmds:
      - golangci-lint run ./...
  sqlc:
    cmds:
      - sqlc generate
  initdata:
    cmds:
      - ./tests/initdata.py
  swagger:
    cmds:
      - swag init -g cmd/main.go
  dev-env-up:
    cmds:
      - docker compose -f dev-compose.yml up -d
  dev-env-down:
    cmds:
      - docker compose -f dev-compose.yml down
